server:  
  port: 8000

spring:  
  application:
    name: agendamentos

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
---
spring.profiles: dev

spring.main.show_banner: false

server.tomcat:
  access-log-enabled: true
  access-log-pattern: "%{X-Forwarded-For}i %l %u %t %r %s %b %{User-Agent}i %{Referer}i - %T"
  basedir: /var/log/inka/tomcat    
