server:  
  port: 8761

spring:  
  application:
    name: discovery

eureka:  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
