server:  
  port: 8000

spring:  
  application:
    name: execucao-service

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
