server:  
  port: 8030

spring:  
  application:
    name: user-info-service

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
